config/routes.rb
Inpirations::Application.routes.draw do
  resources :inspirations

  root 'top#index'
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :users
  

end

app/models/inspiration.rb
class Inspiration < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :trackable, :omniauthable

  has_many :inspirations

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["device.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"]
      end
    end
  end

  def self.find_for_facebook_oauth(auth, sined_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    unless user
      user = User.create(
        name: auth.extra.raw_info.name,
        provider: auth.provider,
        uid: auth.uid,
        password: Devise.friendly_token[0, 20]
      )
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inspirations_controller.rb
class InspirationsController < ApplicationController
  before_action :set_inspiration, only: [:show, :edit, :update, :destroy]

  def index
    @inspirations = Inspiration.all
  end

  def show
  end

  def new
    @inspiration = Inspiration.new(user_id: current_user.id)
  end

  def edit
  end

  def create
    @inspiration = Inspiration.new(inspiration_params)
    @inspiration.user_id = current_user.id

    respond_to do |format|
      if @inspiration.save
        format.html { redirect_to @inspiration, notice: 'Inspiration was successfully created.' }
        format.json { render action: 'show', status: :created, location: @inspiration }
      else
        format.html { render action: 'new' }
        format.json { render json: @inspiration.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @inspiration.update(inspiration_params)
        format.html { redirect_to @inspiration, notice: 'Inspiration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @inspiration.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inspiration.destroy
    respond_to do |format|
      format.html { redirect_to inspirations_url }
      format.json { head :no_content }
    end
  end

  private
    def set_inspiration
      @inspiration = Inspiration.where(user_id: current_user.id).find(params[:id])
    end

    def inspiration_params
      params.require(:inspiration).permit(:title, :contents)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    #TODO: ページング
    @inspirations = Inspiration.all
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "device.omniauth_callbacks.success", kind: "Facebook"
      sign_in_and_redirect @user, event: :authentication
    else
      session["device.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    redirect_to user_path(id: @user.id) unless user_signed_in? && current_user.id == @user.id
  end

  def update
    @user = User.find(params[:id])
    @user.attributes = params.require(:user).permit(:name)

    if @user.save
      redirect_to @user
    else
      render action: edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/inspirations/_form.html.erb
<%= form_for(@inspiration) do |f| %>
  <% if @inspiration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inspiration.errors.count, "error") %> prohibited this inspiration from being saved:</h2>

      <ul>
      <% @inspiration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_area :contents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inspirations/edit.html.erb
<h1>Editing inspiration</h1>

<%= render 'form' %>

<%= link_to 'Show', @inspiration %> |
<%= link_to 'Back', inspirations_path %>

app/views/inspirations/index.html.erb
<h1>Listing inspirations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Contents</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @inspirations.each do |inspiration| %>
      <tr>
        <td><%= inspiration.user_id %></td>
        <td><%= inspiration.title %></td>
        <td><%= inspiration.contents %></td>
        <td><%= link_to 'Show', inspiration %></td>
        <td><%= link_to 'Edit', edit_inspiration_path(inspiration) %></td>
        <td><%= link_to 'Destroy', inspiration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inspiration', new_inspiration_path %>

app/views/inspirations/new.html.erb
<h1>New inspiration</h1>

<%= render 'form' %>

<%= link_to 'Back', inspirations_path %>

app/views/inspirations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @inspiration.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @inspiration.title %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @inspiration.contents %>
</p>

<%= link_to 'Edit', edit_inspiration_path(@inspiration) %> |
<%= link_to 'Back', inspirations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inpirations</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logined as <strong><%= current_user.name %></strong>
      | <%= link_to "Logout", destroy_user_session_path, class: 'navbar-link' %>
    <% else %>
      <%= link_to "Facebook Login", user_omniauth_authorize_path(:facebook), class: 'navbar-link' %>
    <% end %>
    </p>

    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/top/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'write inspiration', new_inspiration_path %>
  <% @inspirations.each do |inspiration| %>
    <hr>
    <%= inspiration.title %>&nbsp;(written by <%= inspiration.user.name %>)<br />
    <%= inspiration.contents %><br />
    <% if current_user == inspiration.user %>
      <%= link_to 'edit', edit_inspiration_path(inspiration) %> |
      <%= link_to 'Destroy', inspiration, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  <% end %>
  <hr>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :name %><br />
  <%= f.submit '更新' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= link_to user.name, user_path(id: user.id) %>
<% end %>

app/views/users/show.html.erb
<%= @user.name %><br />
<% if user_signed_in? && current_user.id == @user.id %>
  <%= link_to '編集', edit_user_path(@user.id) %>
<% end %>